# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Publica-APIS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Publica-APIS
  pod 'Alamofire', '~> 5.2'

  target 'Publica-APISTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
